### ISSUE TITLE
Backport new helper names to v0.2 to avoid dependency hell

### ISSUE THREAD

**Issue by jelhan** [buschtoens/ember-render-helpers#453]
Are you open to backport the helper renaming to v0.2 as well?

Having a v0.2.1 release with the new names in addition to the old once would help with upgrading as addons could support `^0.2.0 || ^1.0.0`. The current setup forces an addon upgrading to v1 dropping support for v0.2 at the same time. Applications using multiple addons which depend on ember-render-helper are forced to upgrade all of them at once. This often slows down upgrading any of them and causes additional work due to amount of changes needed at once.

Every addon could work around using Embroider Macros. But I feel it is easier solving it once by having a v0.2.1 release of ember-render-helpers, which provides the new names as alias.

**Comment by jelhan** [comment]
@buschtoens: Can I interpret your thumbs up as looking forward for a PR?

**Comment by jelhan** [comment]
@ijlee2 Are you open to release such a v0.2 release easing the upgrade path? I have some time working on it tomorrow. But would be great having a confirmation before that you are open to releasing it.

**Comment by ijlee2** [comment]
Hi, @jelhan. I missed the notification from this issue, my bad.

Yes, I agree that releasing `0.2.1` with the new names would help. To confirm, will you create such a pull request, or did you need me to? (I'd prefer the former due to a lack of time.)

Either way, I think it'd be good to call Ember's `deprecate()` method in the helpers with `-helper`. Can you check the format shown in https://github.com/ijlee2/ember-container-query/pull/151/commits/c758c5180ecee9458b1db0a5917be27a402ccbb9 (i.e. call `deprecate()` in the source files in `addon`, not in the re-export files in `app`)?

**Comment by jelhan** [comment]
@ijlee2 I have implemented the changes here: https://github.com/buschtoens/ember-render-helpers/compare/v0.2.0...jelhan:ember-render-helpers:backport-new-helper-names-to-v0.2?expand=1

I branched of from `v0.2.0` tag (71f650b11ffa4f56f848692db2f1cb8a718f6f90).

I cannot create a PR because there isn't a target branch in this repository. Do you mind creating a new branch with name `v0.2.x` or alike based on `v0.2.0` (71f650b11ffa4f56f848692db2f1cb8a718f6f90)? I can create the PR afterwards.

**Comment by ijlee2** [comment]
@jelhan Thanks again for your help. I published `0.2.1`, which should help your migration case.

**Comment by jelhan** [comment]
Thanks a lot. Working as expected.
